### ISSUE TITLE
ability.cooldown_end still sets on_cooldown to false

### ISSUE THREAD

**Issue by lucidmotifs** [lucidmotifs/auto-aoc#2]
shouldn't touch it

**Comment by lucidmotifs** [comment]
`Exception in thread Thread-17:
Traceback (most recent call last):
  File "C:\Users\paulcooper\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\paulcooper\AppData\Local\Programs\Python\Python36\lib\threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\paulcooper\Documents\GitHub\auto-aoc\ability.py", line 215, in cooldown_end
    self.cooling_down = False
AttributeError: can't set attribute`
