### ISSUE TITLE
Cannot set daemon status of active thread exception

### ISSUE THREAD

**Issue by lucidmotifs** [lucidmotifs/auto-aoc#6]
> Traceback (most recent call last):
  File "C:\Users\paulcooper\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\paulcooper\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\paulcooper\Documents\GitHub\auto-aoc\rotation.py", line 430, in q_worker
    item.use(cls)
  File "C:\Users\paulcooper\Documents\GitHub\auto-aoc\ability.py", line 218, in use
    self.init_cooldown()
  File "C:\Users\paulcooper\Documents\GitHub\auto-aoc\ability.py", line 89, in init_cooldown
    self.cooldown.daemon = True
  File "C:\Users\paulcooper\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 1141, in daemon
    raise RuntimeError("cannot set daemon status of active thread")
RuntimeError: cannot set daemon status of active thread

Look into ^^

**Comment by lucidmotifs** [comment]
Happens when  trying to re-start the rotation after do_terminate() is call. By restart - I mean using the hot_key for the rotation.
